version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@fake.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
volumes:
  postgres_data:
#  app:
#    build: .
#    container_name: BlogBackendApp
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - blog-network
#    environment:
#      - MYSQL_HOST=mysql
#      - MYSQL_USER=dbuser
#      - MYSQL_PASSWORD=root
#      - MYSQL_DATABASE=blog
#      - MYSQL_PORT=3306
