version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
      POSTGRES_USER: dbuser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@fake.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
  app:
    build: .
    container_name: Backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
        DATABASE_URL: jdbc:postgresql://postgres:5432/blog
        DATABASE_USER: dbuser
        DATABASE_PASSWORD: password
        JWT_SECRET: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
        JWT_EXPIRATION: 604800000
        FLYWAY_DATABASE_URL: jdbc:postgresql://postgres:5432/blog
        FLYWAY_DATABASE_USER: dbuser
        FLYWAY_DATABASE_PASSWORD: password
volumes:
  postgres_data:

