spring:
    application:
        name: blog
    datasource:
     url: jdbc:mysql://127.0.0.1:3306/blog
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
     database-platform: org.hibernate.dialect.MySQL8Dialect
     show-sql: true
     hibernate:
        ddl-auto: create
    properties:
      javax.persistence.schema-generation.scripts.action: drop-and-create
      jakarta.persistence.schema-generation.scripts.create-target: create.sql
      jakarta.persistence.schema-generation.scripts.drop-target: drop.sql
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}